# pull official base image
FROM node

# set working directory
WORKDIR /app

ARG div_bk_color=green
ENV REACT_APP_DIV_BK_COLOR=$div_bk_color
ENV CHOKIDAR_USEPOLLING=true

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add app
COPY . ./

# start app
CMD ["npm", "start"]
